name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {} 
  push:
    paths:
      - README.md
      - .github/workflows/snake.yml

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation SVG
        uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: mxntchxcbass
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23F7931E&color_dots=%230D1117,%231A1D23,%238B949E,%23C9D1D9,%23F7931E
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%23F7931E&color_dots=%230D1117,%231A1D23,%238B949E,%23C9D1D9,%23F7931E

      - name: Push output to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
